# This file is part of django-walking-settings.
# https://github.com/rflorianobr/django-walking-settings

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Rafael Floriano da Silva <rflorianobr@gmail.com>

language: python

python:
    - "2.7"
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
